/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 japanese_house.glb 
Author: Daniel Stringer (https://sketchfab.com/DanielStringer)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/japanese-house-771899f2af8a4b57aa98b1ca1ae83034
Title: Japanese House
*/

import React from "react";
import { useGLTF } from "@react-three/drei";

export function Japanese(props) {
  const { nodes, materials } = useGLTF("models/japanese_house.glb");
  return (
    <group {...props} dispose={null}>
      <group scale={0.01}>
        <group
          position={[-199.339, 0, -301.235]}
          rotation={[-Math.PI / 2, 0, -Math.PI]}
        >
          <mesh
            geometry={nodes.Glass_Glass_0.geometry}
            material={materials.Glass}
            position={[0, 55.256, 0]}
          />
        </group>
        <group
          position={[0.023, 0, -9.397]}
          rotation={[-Math.PI / 2, 0, -Math.PI / 2]}
        >
          <mesh
            geometry={nodes.JapaneseHouse_House_0.geometry}
            material={materials.House}
            position={[-92.508, -344.106, 0]}
          />
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("models/japanese_house.glb");
